name: dynamic-stage0
channels:
  - rapidsai
  - conda-forge
  - nvidia
  - defaults
dependencies:
  # Core RAPIDS stack (latest stable)
  - rapids=24.06
  - python=3.10
  - cuda-version=12.5
  
  # Development tools
  - jupyterlab
  - ipykernel
  - pytest
  - black
  - flake8
  
  # Additional dependencies (will be installed via pip in deploy script)
  # - SQLAlchemy
  # - PyMySQL
