name: feature-genesis
channels:
  - rapidsai-nightly
  - conda-forge
  - nvidia
  - defaults
dependencies:
  # Core RAPIDS stack (latest nightly with CUDA fixes)
  - rapids=25.06.00a
  - python=3.11
  - cuda-version=12.5
  
  # Core scientific computing
  - numpy>=1.24.0
  - scipy>=1.11.0
  - pandas>=2.0.0
  
  # GPU acceleration and optimization
  - numba>=0.58.0
  - cusignal>=23.8.0
  - cupyx-scipy>=13.0.0
  
  # Statistical and mathematical libraries
  - statsmodels>=0.14.0
  - scikit-learn>=1.3.0
  - lightgbm>=4.0.0
  - catboost>=1.2.5
  
  # Data I/O and storage
  - pyarrow>=12.0.0
  - boto3>=1.28.0
  - s3fs>=2023.6.0
  
  # Database connectivity
  - sqlalchemy>=2.0.0
  - pymysql>=1.1.0
  - cryptography>=41.0.0
  
  # Configuration and utilities
  - pyyaml>=6.0
  - python-dotenv>=1.0.0
  - click>=8.1.0
  
  # Logging and monitoring
  - structlog>=23.1.0
  - rich>=13.4.0
  - psutil>=5.9.0
  - python-json-logger>=2.0.7
  
  # Development tools
  - jupyterlab
  - ipykernel
  - pytest>=7.4.0
  - pytest-asyncio>=0.21.0
  - pytest-cov>=4.1.0
  - black>=23.0.0
  - flake8>=6.0.0
  - mypy>=1.5.0
  - isort>=5.12.0
  
  # Performance monitoring
  - memory-profiler>=0.61.0
  - gputil>=1.4.0
  
  # Network and communication
  - aiohttp>=3.8.0
  - websockets>=11.0.0
  
  # Security
  - bcrypt>=4.0.0
  
  # Visualization (for debugging and analysis)
  - plotly>=5.15.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  
  # Time series analysis
  - tslearn>=0.6.0
  
  # Signal processing
  - pywt>=1.4.0
  
  # Distributed computing
  - ray>=2.6.0
  
  # Monitoring and observability
  - prometheus-client>=0.17.0
  
  # Configuration management
  - hydra-core>=1.3.0
  - omegaconf>=2.3.0
  
  # Data versioning
  - dvc>=3.0.0
  - mlflow>=2.6.0
  
  # Code quality
  - pre-commit>=3.3.0
  
  # Documentation
  - sphinx>=7.0.0
  - sphinx-rtd-theme>=1.3.0
  
  # Jupyter support
  - ipywidgets>=8.0.0
  
  # API development
  - fastapi>=0.100.0
  - uvicorn>=0.23.0
  - pydantic>=2.0.0
  
  # Task scheduling
  - celery>=5.3.0
  - redis>=4.6.0
  
  # Message queuing
  - kafka-python>=2.0.0
  - pika>=1.3.0
  
  # Cloud platform support
  - google-cloud-storage>=2.10.0
  - azure-storage-blob>=12.17.0
  
  # Additional dependencies (will be installed via pip in deploy script)
  # - dcor>=0.5.3
  # - emd>=0.5.1
  # - arch>=6.2.0
  # - great-expectations>=0.17.0
  # - joblib>=1.3.0
  # - multiprocessing-logging>=0.3.0
  # - backup-utils>=0.1.0
  # - xgboost>=1.7.0
  # - pykalman>=0.9.5
  # - librosa>=0.10.0
  # - horovod>=0.28.0
  # - jaeger-client>=4.8.0
  # - kubernetes>=27.0.0
  # - aws-sdk-python>=1.28.0
