# Dynamic Stage 0 - Unified Configuration File
# GPU-Accelerated Feature Engineering Pipeline
# 
# This configuration file consolidates all settings for the pipeline including:
# - Database connectivity
# - Cloud storage (R2)
# - Dask-CUDA cluster settings
# - Feature engineering parameters
# - Processing pipeline configuration
# - Error handling and monitoring
# - Development and debugging options

# Database Configuration
# MySQL database connection settings for task tracking and metadata
database:
  host: ${MYSQL_HOST:localhost}
  port: ${MYSQL_PORT:3010}
  database: ${MYSQL_DATABASE:feature_genesis_db}
  username: ${MYSQL_USERNAME:root}
  password: ${MYSQL_PASSWORD:root}
  charset: utf8mb4
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600

# Cloudflare R2 Storage Configuration
# Cloud storage settings for data input/output
r2:
  account_id: ${R2_ACCOUNT_ID:ac68ac775ba99b267edee7f9b4b3bc4e}
  access_key: ${R2_ACCESS_KEY:0e315105695707ca4fe1e5f83a38f807}
  secret_key: ${R2_SECRET_KEY:5fbf8a2121f48807fdd3abc1c63c28cae6b67424f01e8d20a9cc68b1d47ca515}
  bucket_name: ${R2_BUCKET_NAME:camaleon}
  endpoint_url: ${R2_ENDPOINT_URL:https://ac68ac775ba99b267edee7f9b4b3bc4e.r2.cloudflarestorage.com}
  region: auto

# Dask-CUDA Cluster Configuration
# GPU cluster settings for distributed processing
dask:
  # Worker configuration
  gpus_per_worker: 1
  threads_per_worker: 1
  memory_limit: "8GB"
  
  # RMM (RAPIDS Memory Manager) settings
  rmm_pool_size: "4GB"
  rmm_initial_pool_size: "4GB"
  rmm_maximum_pool_size: "8GB"
  spilling_enabled: true
  spilling_target: 0.9
  spilling_max_spill: "32GB"
  
  # Memory management
  memory_target_fraction: 0.8
  memory_spill_fraction: 0.9
  local_directory: "/tmp/dask-worker-space"
  
  # Network protocol settings
  protocol: "ucx"
  enable_tcp_over_ucx: true
  enable_infiniband: false
  enable_nvlink: true

# Feature Engineering Configuration
# Parameters for all feature engineering engines
features:
  # Rolling window configurations for various calculations
  rolling_windows: [10, 20, 50, 100, 200]
  rolling_min_periods: 1
  
  # Rolling correlation configuration
  rolling_corr:
    windows: [15, 30, 60]
    min_periods: 1
  
  # Fractional differentiation configuration
  frac_diff:
    d_values: [0.1, 0.2, 0.3, 0.4, 0.5]
    threshold: 1e-5
    max_lag: 1000
  
  # Baxter-King filter configuration
  baxter_king:
    low_freq: 6
    high_freq: 32
    k: 12
  
  # GARCH model configuration
  garch:
    p: 1
    q: 1
    max_iter: 1000
    tolerance: 1e-6
  
  # Distance correlation configuration
  distance_corr:
    max_samples: 1000
  
  # Empirical Mode Decomposition configuration
  emd:
    max_imfs: 10
    tolerance: 1e-8
    max_iterations: 100
  
  # Statistical tests parameters
  distance_corr_max_samples: 1000
  distance_corr_tile_size: 2048
  selection_target_column: y_ret_fwd_15m
  # Optional list to run multi-target sweep (per run, per pair)
  selection_target_columns: []
  dcor_top_k: 50
  dcor_include_permutation: true
  dcor_permutations: 100
  selection_max_rows: 100000
  vif_threshold: 5.0
  mi_threshold: 0.3
  stage3_top_n: 50
  # Stage 3 wrappers (LightGBM)
  stage3_task: auto  # auto|regression|classification
  stage3_random_state: 42
  stage3_lgbm_enabled: true
  stage3_lgbm_num_leaves: 31
  stage3_lgbm_max_depth: -1
  stage3_lgbm_n_estimators: 200
  stage3_lgbm_learning_rate: 0.05
  stage3_lgbm_feature_fraction: 0.8
  stage3_lgbm_bagging_fraction: 0.8
  stage3_lgbm_bagging_freq: 0
  stage3_lgbm_early_stopping_rounds: 0
  stage3_use_gpu: true
  stage3_wrapper_backend: xgb_gpu  # lgbm|xgb_gpu
  dcor_min_threshold: 0.05
  dcor_min_percentile: 0.0
  stage1_top_n: 100
  dcor_fast_1d_enabled: true
  dcor_fast_1d_bins: 2048
  dcor_permutation_top_k: 50
  dcor_permutations: 100
  dcor_pvalue_alpha: 0.05
  # Stage 1 batching for progress visibility
  dcor_batch_size: 64
  # Stage 1 rolling dCor (exposed)
  stage1_rolling_enabled: true
  stage1_rolling_window: 2000
  stage1_rolling_step: 500
  stage1_rolling_min_periods: 200
  # Minimum pairwise valid observations per rolling window (handles sparse/off-hours data)
  stage1_rolling_min_valid_pairs: 200
  stage1_rolling_max_rows: 20000
  stage1_rolling_max_windows: 20
  stage1_agg: median  # mean|median|min|max|p25|p75
  stage1_use_rolling_scores: true
  # Dataset schema/feature gating (leakage control)
  dataset_target_columns: []         # list of label/target columns present in the dataset
  dataset_target_prefixes: ["m1_", "m2_", "m3_", "m4_", "m5_", "m6_", "m7_", "m8_", "m9_"]  # model targets m1..m9
  feature_allowlist: []              # exact feature names allowed (if non-empty, acts as allowlist)
  feature_allow_prefixes: []         # prefixes allowed (any match passes allowlist)
  feature_denylist: ["y_tick_volume", "y_total_volume"]  # exclude raw volume features
  feature_deny_prefixes: ["y_ret_fwd_"]  # exclude all forward-return labels by default
  feature_deny_regex: []             # regex patterns to exclude (optional)
  metrics_prefixes: ["dcor_", "dcor_roll_", "dcor_pvalue_", "stage1_", "cpcv_"]
  # Visibility controls
  stage1_broadcast_scores: false   # if true, add dcor_* columns (1 per feature)
  stage1_broadcast_rolling: false  # if true, add dcor_roll_* and dcor_roll_cnt_* columns
  debug_write_artifacts: true      # persist JSON artifacts for transparency
  artifacts_dir: artifacts         # subfolder under output_path
  # Fractional diff cache/tuning (exposed)
  fracdiff_cache_max_entries: 32
  fracdiff_partition_threshold: 4096
  # MI clustering (Stage 2) scalable options
  mi_cluster_enabled: true
  mi_cluster_method: agglo
  mi_cluster_threshold: 0.3
  mi_max_candidates: 400
  mi_chunk_size: 128
  cpcv_enabled: true
  cpcv_n_groups: 6
  cpcv_k_leave_out: 2
  cpcv_purge: 0
  cpcv_embargo: 0
  adf_alpha: 0.05
  # Stage 1 explicit candidates (no regex)
  station_candidates_include:
    # OHLC níveis e derivados de nível
    - y_open
    - y_high
    - y_low
    - y_close
    - y_weighted_close
    - y_typical_price
    # Médias móveis (nível)
    - y_sma_20
    - y_sma_60
    - y_ema_12
    - y_ema_26
    # VWAP e distâncias (nível)
    - y_vwap_20
    - y_vwap_distance
    - y_vwap_60m_distance
    # Bollinger (nível/largura)
    - y_bb_lower_20_2
    - y_bb_upper_20_2
    - y_bb_width_20
    # Volatilidade/Range
    - y_atr_14
    - y_true_range
    - y_parkinson_30m
    - y_garman_klass_vol
    - y_gk_vol_30m
    - y_rv_30m
    - y_tick_volatility
    # Donchian (nível/largura)
    - y_donchian_channels_20
    - y_donchian_lower_20
    - y_donchian_upper_20
    - y_donchian_width_20
    # Spreads (nível)
    - y_avg_spread
    - y_max_spread
    - y_min_spread
    - y_spread_lvl
    # Morfologia / preços derivados (nível)
    - y_body_size
    - y_range_size
    - y_range_pct
    - y_gap_open
    - y_price_change
    - y_price_changes_count
    - y_price_velocity
  station_candidates_exclude:
    - y_avg_spread_relative
    - y_spread_rel
    - y_spread_rel_z_15m
    - y_close_z_60m
    - y_close_z_240m
    - y_z_60m_close
    - y_z_240m_close
    - y_obv_z_60m
    - y_atr_z_60m
    - y_tr_z_60m
    - y_vwap_60m_distance_slope
    - y_corr_30m
    - y_corr_60m
    - y_corr_dxy_1h
    - y_corr_dxy_4h
    - y_beta_240m
    - beta240_y_on_brent
    - beta240_y_on_dxy
    - beta240_y_on_spx
    - corr30_ofi_y_dxy
    - corr30_ret_ofi_y
    - corr30_tickvol_y_spx
    - corr60_y_dxy
    - corr60_y_spx
    - y_interaction_spread_ofi
    - y_interaction_vol_beta
    # Targets / leakage guard (já cobertos por outras listas de negação)
    - y_ret_fwd_1m
    - y_ret_fwd_3m
    - y_ret_fwd_5m
    - y_ret_fwd_10m
    - y_ret_fwd_15m
    - y_ret_fwd_20m
    - y_ret_fwd_30m
    - y_ret_fwd_60m
    - y_ret_fwd_120m
    - y_ret_fwd_240m
  # If true, drops original columns after creating frac_diff_<col>
  drop_original_after_transform: true
  # If true, drops features that didn't pass Stage 1 retention gates
  drop_nonretained_after_stage1: true

# Processing Pipeline Configuration
# Settings for data processing and pipeline execution
processing:
  batch_size: 1000
  chunk_size: "100MB"
  max_workers: 4
  timeout: 1800  # 30 minutes
  continue_on_error: false
  fail_fast: true

# Logging Configuration
# Logging settings for monitoring and debugging
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "pipeline.log"
  max_size: "100MB"
  backup_count: 5

# Monitoring Configuration
# Performance monitoring and metrics collection
monitoring:
  metrics_enabled: true
  dashboard_port: 8787
  health_check_interval: 30

# Output Configuration
# Data output settings and file formats
output:
  output_path: "./output"
  compression: "lz4"
  format: "feather"
  version: 2

# Development Configuration
# Development and debugging options
development:
  debug_mode: false
  clean_existing_output: false
  force_reprocessing: false
  enable_profiling: false
  log_memory_usage: true
  validate_data: true

# Pipeline Engine Configuration
# Individual engine settings and execution order
pipeline:
  engines:
    stationarization:
      enabled: true
      order: 1
      description: "Stationarization techniques including fractional differentiation"
      timeout: 300
      retry_count: 3
    statistical_tests:
      enabled: true
      order: 2
      description: "Statistical tests and analysis"
      timeout: 300
      retry_count: 3
    signal_processing:
      enabled: true
      order: 3
      description: "Signal processing features"
      timeout: 300
      retry_count: 3
    garch_models:
      enabled: true
      order: 4
      description: "GARCH volatility modeling"
      timeout: 300
      retry_count: 3

# Error Handling Configuration
# Error handling and recovery settings
error_handling:
  continue_on_error: false
  max_retries: 3
  retry_delay: 5
  critical_error_threshold: 1

# Memory Management Configuration
# Advanced memory management settings
memory:
  # RMM Configuration
  rmm_pool_size_gb: 8.0
  rmm_initial_pool_size_gb: 4.0
  rmm_maximum_pool_size_gb: 16.0
  rmm_memory_target_fraction: 0.8
  rmm_memory_spill_threshold: 0.9
  
  # Chunked processing settings
  chunk_size: 10000
  chunk_overlap: 1000
  max_memory_gb: 8.0
  
  # Spilling configuration
  enable_spilling: true
  spill_to_disk: true
  spill_directory: "/tmp/gpu_spill"
  
  # Memory monitoring
  monitor_memory: true
  alert_threshold: 0.9
  check_interval: 10

# Performance Optimization Configuration
# GPU and computation optimization settings
optimization:
  # GPU optimization
  use_float32: true
  optimize_column_order: true
  avoid_cpu_transfers: true
  
  # Kernel optimization
  enable_custom_kernels: true
  kernel_compilation_timeout: 60
  
  # Memory optimization
  batch_processing: true
  batch_size: 1000
  cleanup_after_batch: true
  
  # Convolution optimization
  use_fft_for_large_kernels: true
  fft_threshold: 129

# Data Validation Configuration
# Data quality and validation settings
validation:
  # Input validation
  validate_input_data: true
  required_columns: ["timestamp", "open", "high", "low", "close", "volume"]
  expected_dtypes:
    timestamp: "datetime64[ns]"
    open: "float32"
    high: "float32"
    low: "float32"
    close: "float32"
    volume: "float32"
  
  # Output validation
  validate_output_data: true
  max_nan_percentage: 50.0
  check_infinite_values: true
  
  # Data quality thresholds
  min_rows: 100
  max_missing_percentage: 20.0
  outlier_threshold: 3.0

# Security Configuration
# Security and access control settings
security:
  # Database security
  use_ssl: false
  verify_ssl: true
  
  # R2 security
  use_encryption: true
  encryption_algorithm: "AES256"
  
  # Access control
  require_authentication: true
  session_timeout: 3600

# Backup and Recovery Configuration
# Data backup and recovery settings
backup:
  # Backup settings
  enable_backup: true
  backup_interval: 3600  # 1 hour
  backup_retention_days: 7
  
  # Recovery settings
  enable_auto_recovery: true
  recovery_checkpoint_interval: 300  # 5 minutes
  
  # Storage settings
  backup_directory: "./backups"
  compression: "gzip"
